import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | null>(null);

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.patients': 'Patients',
    'nav.dashboard': 'Dashboard',
    'nav.statistics': 'Statistics',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',
    'nav.login': 'Please log in',
    
    // Common
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.actions': 'Actions',
    'common.back': 'Back',
    'common.viewAll': 'View All',
    'common.loading': 'Loading...',
    'common.noData': 'No data found',
    'common.confirmDelete': 'Are you sure you want to delete this?',
    'common.required': 'is required',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'common.page': 'Page',
    'common.of': 'of',
    'common.perPage': 'per page',
    'common.total': 'total',
    
    // Login
    'login.title': 'Login',
    'login.subtitle': 'Welcome to SurgiCare',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.emailPlaceholder': 'Enter your email',
    'login.passwordPlaceholder': 'Enter your password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing In...',
    'login.error': 'Invalid email or password',
    'login.welcomeBack': 'Welcome back!',
    
    // Dashboard
    'dashboard.title': 'Hospital Dashboard',
    'dashboard.subtitle': 'Welcome to the Hospital Management System. Monitor key metrics and manage patient records.',
    'dashboard.totalPatients': 'Total Patients',
    'dashboard.diagnosed': 'Diagnosed',
    'dashboard.preOp': 'Pre-op',
    'dashboard.postOp': 'Post-op',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.viewAllPatients': 'View All Patients',
    'dashboard.viewAllPatientsDesc': 'Browse and manage patient records',
    'dashboard.viewStatistics': 'View Statistics',
    'dashboard.viewStatisticsDesc': 'Analyze patient data and trends',
    'dashboard.adminPanel': 'Admin Panel',
    'dashboard.adminPanelDesc': 'Manage users and system settings',
    'dashboard.recentPatients': 'Recent Patients',
    'dashboard.diagnosisDistribution': 'Diagnosis Distribution',
    'dashboard.exportPDF': 'Export Dashboard PDF',
    
    // Patients
    'patients.title': 'Patient Records',
    'patients.subtitle': 'Manage and track patient information with comprehensive medical records',
    'patients.addPatient': 'Add Patient',
    'patients.editPatient': 'Edit Patient',
    'patients.patientCode': 'Patient Code',
    'patients.fullName': 'Full Name',
    'patients.age': 'Age',
    'patients.gender': 'Gender',
    'patients.diagnosis': 'Diagnosis',
    'patients.visitedDate': 'Visited Date',
    'patients.status': 'Status',
    'patients.searchPlaceholder': 'Search patients by name, code, or diagnosis...',
    'patients.allDiagnoses': 'All Diagnoses',
    'patients.allStatus': 'All Status',
    'patients.allYears': 'All Years',
    'patients.allMonths': 'All Months',
    'patients.exportPDF': 'Export PDF',
    'patients.noPatients': 'No patients found matching your criteria.',
    'patients.clickToView': 'Click to view full details',
    'patients.yearsOld': 'years old',
    'patients.patientDeleted': 'Patient record has been removed',
    'patients.exportComplete': 'Patient records exported successfully',
    'patients.exportFailed': 'Unable to generate PDF. Please check your connection and try again.',
    
    // Patient Form
    'form.basicInfo': 'Basic Information',
    'form.contactInfo': 'Contact Information',
    'form.personalImage': 'Personal Image',
    'form.surgeryImage': 'Surgery Image',
    'form.radiologyFiles': 'Radiology Files',
    'form.labFiles': 'Lab Files',
    'form.surgeries': 'Surgeries',
    'form.followUps': 'Follow-ups',
    'form.fullNameEn': 'Full Name (English)',
    'form.fullNameAr': 'Full Name (Arabic)',
    'form.age': 'Age',
    'form.gender': 'Gender',
    'form.diagnosisCategory': 'Diagnosis Category',
    'form.diagnosis': 'Diagnosis',
    'form.visitedDate': 'Visited Date',
    'form.status': 'Status',
    'form.notes': 'Notes',
    'form.contactName': 'Contact Name',
    'form.phone': 'Phone',
    'form.email': 'Email',
    'form.relation': 'Relation',
    'form.address': 'Address',
    'form.uploadPersonalPhoto': 'Upload Personal Photo',
    'form.uploadSurgeryImage': 'Upload Surgery Image',
    'form.uploadRadiology': 'Upload Radiology Files',
    'form.uploadLab': 'Upload Lab Files',
    'form.surgeryDate': 'Surgery Date',
    'form.surgeryType': 'Surgery Type',
    'form.surgeryNotes': 'Surgery Notes',
    'form.surgeons': 'Surgeons',
    'form.addSurgeon': 'Add Surgeon',
    'form.surgeonName': 'Surgeon name',
    'form.specialization': 'Specialization',
    'form.surgeryCost': 'Surgery Cost',
    'form.addSurgery': 'Add Surgery',
    'form.followUpDate': 'Date',
    'form.followUpNotes': 'Follow-up notes',
    'form.addFollowUp': 'Add Follow-up',
    'form.addPatient': 'Add New Patient',
    'form.updatePatient': 'Update Patient',
    'form.uploading': 'Uploading files...',
    'form.saving': 'Saving...',
    'form.patientAdded': 'New patient has been added to the system',
    'form.patientUpdated': 'Patient information has been updated',
    'form.saveError': 'Unable to save patient information. Please check your connection and try again.',
    'form.selectCategory': 'Select Category',
    'form.selectDiagnosis': 'Select Diagnosis',
    'form.enterDiagnosis': 'Enter diagnosis',
    'form.filesSelected': 'file(s) selected',
    
    // Patient Detail
    'detail.basicInfo': 'Basic Information',
    'detail.dates': 'Dates',
    'detail.medicalNotes': 'Medical Notes',
    'detail.contactInfo': 'Contact Information',
    'detail.surgeryDetails': 'Surgery Details',
    'detail.filesAndImages': 'Medical Files & Images',
    'detail.personalImage': 'Personal Image',
    'detail.surgeryImage': 'Surgery Image',
    'detail.radiologyFiles': 'Radiology Files',
    'detail.labFiles': 'Lab Files',
    'detail.viewFullSize': 'Click to view full size',
    'detail.noFiles': 'No medical files or images uploaded',
    'detail.patientNotFound': 'Patient not found',
    'detail.backToPatients': 'Back to Patients',
    'detail.surgeryDate': 'Surgery Date',
    'detail.surgeryType': 'Surgery Type',
    'detail.cost': 'Cost',
    'detail.followUp': 'Follow-up',
    'detail.quickStats': 'Quick Statistics',
    'detail.surgeriesCount': 'Total Surgeries',
    'detail.followUpsCount': 'Follow-up Visits',
    'detail.filesCount': 'Medical Files',
    'detail.surgery': 'Surgery',
    'detail.viewRadiology': 'View Radiology',
    'detail.viewLabFile': 'View Lab File',
    'detail.exportPDF': 'Export Patient PDF',
    'detail.exportingPDF': 'Generating PDF...',
    'detail.pdfExported': 'Patient PDF exported successfully',
    'detail.pdfError': 'Failed to generate PDF. Please try again.',
    
    // Statistics
    'stats.title': 'Statistics & Analytics',
    'stats.subtitle': 'Comprehensive analysis of patient data and trends',
    'stats.totalPatients': 'Total Patients',
    'stats.activeCases': 'Active Cases',
    'stats.thisMonth': 'This Month',
    'stats.diagnoses': 'Diagnoses',
    'stats.diagnosisDistribution': 'Diagnosis Distribution',
    'stats.patientStatus': 'Patient Status',
    'stats.monthlyTrends': 'Monthly Admissions Trend',
    'stats.ageDistribution': 'Age Distribution',
    'stats.detailedStats': 'Detailed Statistics',
    'stats.mostCommonDiagnosis': 'Most Common Diagnosis',
    'stats.averageAge': 'Average Age',
    'stats.recoveryRate': 'Recovery Rate',
    'stats.peakMonth': 'Peak Month',
    'stats.exportJSON': 'Export JSON',
    'stats.exportPDF': 'Export PDF',
    'stats.years': 'years',
    
    // Admin
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Manage users and control system access',
    'admin.totalUsers': 'Total Users',
    'admin.administrators': 'Administrators',
    'admin.financialAccess': 'Financial Access',
    'admin.userManagement': 'User Management',
    'admin.addUser': 'Add User',
    'admin.editUser': 'Edit User',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    
    'admin.enabled': 'Enabled',
    'admin.disabled': 'Disabled',
    'admin.grantAccess': 'Grant access to financial section',
    'admin.financialAccessDesc': 'Users with this permission can view surgery costs and financial information',
    'admin.fullName': 'Full Name',
    'admin.emailAddress': 'Email Address',
    'admin.password': 'Password',
    'admin.keepPassword': 'Leave blank to keep current password',
    'admin.user': 'User',
    'admin.doctor': 'Doctor',
    'admin.administrator': 'Administrator',
    'admin.noUsers': 'No users found. Add your first user.',
    'admin.cannotDeleteSelf': 'You cannot delete your own account',
    'admin.confirmDeleteUser': 'Are you sure you want to delete this user?',
    'admin.deleteUser': 'Delete User',
    'admin.userCreated': 'New user account has been created',
    'admin.userUpdated': 'User account has been updated',
    'admin.userDeleted': 'User account has been removed',
    'admin.saveError': 'Unable to save user account. Please check your connection and try again.',
    'admin.deleteError': 'Unable to remove user account. Please try again.',
    'admin.financialAccessGranted': 'Financial access has been granted',
    'admin.financialAccessRevoked': 'Financial access has been revoked',
    'admin.accessUpdateError': 'Unable to update access permissions. Please try again.',
    'admin.dataManagement': 'Data Management',
    'admin.exportDatabase': 'Export Database',
    'admin.importPatients': 'Import Patients',
    'admin.exporting': 'Exporting...',
    'admin.importing': 'Importing...',
    'admin.exportSuccess': 'Database exported successfully',
    'admin.exportError': 'Failed to export database',
    'admin.importSuccess': 'Patients imported successfully',
    'admin.importError': 'Failed to import patients',
    'admin.importNoData': 'No valid patient data found in file',
    'admin.importPartial': 'Some patients failed to import',
    'admin.exportInfo': 'Export:',
    'admin.exportDescription': 'Download complete database as JSON for backup or migration.',
    'admin.importInfo': 'Import:',
    'admin.importDescription': 'Import patients from CSV/Excel file. Required columns: Name (Arabic), Age, Gender, Diagnosis, Date, Status, Notes.',
    
    // Status
    'status.diagnosed': 'Diagnosed',
    'status.preOp': 'Pre-op',
    'status.postOp': 'Post-op',
    
    // Gender
    'gender.male': 'Male',
    'gender.female': 'Female',
    'gender.other': 'Other',
  },
  ar: {
    // Navigation
    'nav.patients': 'المرضى',
    'nav.dashboard': 'لوحة التحكم',
    'nav.statistics': 'الإحصائيات',
    'nav.admin': 'الإدارة',
    'nav.logout': 'تسجيل الخروج',
    'nav.login': 'يرجى تسجيل الدخول',
    
    // Common
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.close': 'إغلاق',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.actions': 'الإجراءات',
    'common.back': 'رجوع',
    'common.viewAll': 'عرض الكل',
    'common.loading': 'جاري التحميل...',
    'common.noData': 'لا توجد بيانات',
    'common.confirmDelete': 'هل أنت متأكد من حذف هذا؟',
    'common.required': 'مطلوب',
    'common.previous': 'السابق',
    'common.next': 'التالي',
    'common.page': 'صفحة',
    'common.of': 'من',
    'common.perPage': 'لكل صفحة',
    'common.total': 'إجمالي',
    
    // Login
    'login.title': 'تسجيل الدخول',
    'login.subtitle': 'مرحباً بك في SurgiCare',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.emailPlaceholder': 'أدخل بريدك الإلكتروني',
    'login.passwordPlaceholder': 'أدخل كلمة المرور',
    'login.signIn': 'تسجيل الدخول',
    'login.signingIn': 'جاري تسجيل الدخول...',
    'login.error': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    'login.welcomeBack': 'مرحباً بعودتك!',
    
    // Dashboard
    'dashboard.title': 'لوحة تحكم المستشفى',
    'dashboard.subtitle': 'مرحباً بك في نظام إدارة المستشفى. راقب المقاييس الرئيسية وأدرج سجلات المرضى.',
    'dashboard.totalPatients': 'إجمالي المرضى',
    'dashboard.diagnosed': 'مشخص',
    'dashboard.preOp': 'قبل الجراحة',
    'dashboard.postOp': 'بعد الجراحة',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.viewAllPatients': 'عرض جميع المرضى',
    'dashboard.viewAllPatientsDesc': 'تصفح وإدارة سجلات المرضى',
    'dashboard.viewStatistics': 'عرض الإحصائيات',
    'dashboard.viewStatisticsDesc': 'تحليل بيانات المرضى والاتجاهات',
    'dashboard.adminPanel': 'لوحة الإدارة',
    'dashboard.adminPanelDesc': 'إدارة المستخدمين وإعدادات النظام',
    'dashboard.recentPatients': 'المرضى الأخيرون',
    'dashboard.diagnosisDistribution': 'توزيع التشخيص',
    'dashboard.exportPDF': 'تصدير تقرير PDF',
    
    // Patients
    'patients.title': 'سجلات المرضى',
    'patients.subtitle': 'إدارة وتتبع معلومات المرضى مع السجلات الطبية الشاملة',
    'patients.addPatient': 'إضافة مريض',
    'patients.editPatient': 'تعديل مريض',
    'patients.patientCode': 'رمز المريض',
    'patients.fullName': 'الاسم الكامل',
    'patients.age': 'العمر',
    'patients.gender': 'الجنس',
    'patients.diagnosis': 'التشخيص',
    'patients.visitedDate': 'تاريخ الزيارة',
    'patients.status': 'الحالة',
    'patients.searchPlaceholder': 'البحث عن المرضى بالاسم أو الرمز أو التشخيص...',
    'patients.allDiagnoses': 'جميع التشخيصات',
    'patients.allStatus': 'جميع الحالات',
    'patients.allYears': 'جميع السنوات',
    'patients.allMonths': 'جميع الأشهر',
    'patients.exportPDF': 'تصدير PDF',
    'patients.noPatients': 'لم يتم العثور على مرضى يطابقون معاييرك.',
    'patients.clickToView': 'انقر لعرض التفاصيل الكاملة',
    'patients.yearsOld': 'سنة',
    'patients.patientDeleted': 'تم حذف سجل المريض',
    'patients.exportComplete': 'تم تصدير سجلات المرضى بنجاح',
    'patients.exportFailed': 'تعذر إنشاء ملف PDF. يرجى التحقق من الاتصال والمحاولة مرة أخرى.',
    
    // Patient Form
    'form.basicInfo': 'المعلومات الأساسية',
    'form.contactInfo': 'معلومات الاتصال',
    'form.personalImage': 'الصورة الشخصية',
    'form.surgeryImage': 'صورة الجراحة',
    'form.radiologyFiles': 'ملفات الأشعة',
    'form.labFiles': 'ملفات المختبر',
    'form.surgeries': 'الجراحات',
    'form.followUps': 'المتابعات',
    'form.fullNameEn': 'الاسم الكامل (بالإنجليزية)',
    'form.fullNameAr': 'الاسم الكامل (بالعربية)',
    'form.age': 'العمر',
    'form.gender': 'الجنس',
    'form.diagnosisCategory': 'فئة التشخيص',
    'form.diagnosis': 'التشخيص',
    'form.visitedDate': 'تاريخ الزيارة',
    'form.status': 'الحالة',
    'form.notes': 'ملاحظات',
    'form.contactName': 'اسم جهة الاتصال',
    'form.phone': 'الهاتف',
    'form.email': 'البريد الإلكتروني',
    'form.relation': 'العلاقة',
    'form.address': 'العنوان',
    'form.uploadPersonalPhoto': 'رفع الصورة الشخصية',
    'form.uploadSurgeryImage': 'رفع صورة الجراحة',
    'form.uploadRadiology': 'رفع ملفات الأشعة',
    'form.uploadLab': 'رفع ملفات المختبر',
    'form.surgeryDate': 'تاريخ الجراحة',
    'form.surgeryType': 'نوع الجراحة',
    'form.surgeryNotes': 'ملاحظات الجراحة',
    'form.surgeons': 'الجراحون',
    'form.addSurgeon': 'إضافة جراح',
    'form.surgeonName': 'اسم الجراح',
    'form.specialization': 'التخصص',
    'form.surgeryCost': 'تكلفة الجراحة',
    'form.addSurgery': 'إضافة جراحة',
    'form.followUpDate': 'التاريخ',
    'form.followUpNotes': 'ملاحظات المتابعة',
    'form.addFollowUp': 'إضافة متابعة',
    'form.addPatient': 'إضافة مريض جديد',
    'form.updatePatient': 'تحديث المريض',
    'form.uploading': 'جاري رفع الملفات...',
    'form.saving': 'جاري الحفظ...',
    'form.patientAdded': 'تم إضافة مريض جديد إلى النظام',
    'form.patientUpdated': 'تم تحديث معلومات المريض',
    'form.saveError': 'تعذر حفظ معلومات المريض. يرجى التحقق من الاتصال والمحاولة مرة أخرى.',
    'form.selectCategory': 'اختر الفئة',
    'form.selectDiagnosis': 'اختر التشخيص',
    'form.enterDiagnosis': 'أدخل التشخيص',
    'form.filesSelected': 'ملف(ات) محدد',
    
    // Patient Detail
    'detail.basicInfo': 'المعلومات الأساسية',
    'detail.dates': 'التواريخ',
    'detail.medicalNotes': 'الملاحظات الطبية',
    'detail.contactInfo': 'معلومات الاتصال',
    'detail.surgeryDetails': 'تفاصيل الجراحة',
    'detail.filesAndImages': 'الملفات والصور الطبية',
    'detail.personalImage': 'الصورة الشخصية',
    'detail.surgeryImage': 'صورة الجراحة',
    'detail.radiologyFiles': 'ملفات الأشعة',
    'detail.labFiles': 'ملفات المختبر',
    'detail.viewFullSize': 'انقر لعرض الحجم الكامل',
    'detail.noFiles': 'لم يتم رفع ملفات أو صور طبية',
    'detail.patientNotFound': 'المريض غير موجود',
    'detail.backToPatients': 'رجوع إلى المرضى',
    'detail.surgeryDate': 'تاريخ الجراحة',
    'detail.surgeryType': 'نوع الجراحة',
    'detail.cost': 'التكلفة',
    'detail.followUp': 'متابعة',
    'detail.quickStats': 'إحصائيات سريعة',
    'detail.surgeriesCount': 'إجمالي الجراحات',
    'detail.followUpsCount': 'زيارات المتابعة',
    'detail.filesCount': 'الملفات الطبية',
    'detail.surgery': 'جراحة',
    'detail.viewRadiology': 'عرض الأشعة',
    'detail.viewLabFile': 'عرض ملف المختبر',
    'detail.exportPDF': 'تصدير ملف PDF للمريض',
    'detail.exportingPDF': 'جاري إنشاء ملف PDF...',
    'detail.pdfExported': 'تم تصدير ملف PDF للمريض بنجاح',
    'detail.pdfError': 'فشل إنشاء ملف PDF. يرجى المحاولة مرة أخرى.',
    
    // Statistics
    'stats.title': 'الإحصائيات والتحليلات',
    'stats.subtitle': 'تحليل شامل لبيانات المرضى والاتجاهات',
    'stats.totalPatients': 'إجمالي المرضى',
    'stats.activeCases': 'الحالات النشطة',
    'stats.thisMonth': 'هذا الشهر',
    'stats.diagnoses': 'التشخيصات',
    'stats.diagnosisDistribution': 'توزيع التشخيص',
    'stats.patientStatus': 'حالة المريض',
    'stats.monthlyTrends': 'اتجاه القبولات الشهرية',
    'stats.ageDistribution': 'توزيع العمر',
    'stats.detailedStats': 'إحصائيات مفصلة',
    'stats.mostCommonDiagnosis': 'التشخيص الأكثر شيوعاً',
    'stats.averageAge': 'متوسط العمر',
    'stats.recoveryRate': 'معدل الشفاء',
    'stats.peakMonth': 'الشهر الذروة',
    'stats.exportJSON': 'تصدير JSON',
    'stats.exportPDF': 'تصدير PDF',
    'stats.years': 'سنة',
    
    // Admin
    'admin.title': 'لوحة تحكم الإدارة',
    'admin.subtitle': 'إدارة المستخدمين والتحكم في وصول النظام',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.administrators': 'المسؤولون',
    'admin.financialAccess': 'الوصول المالي',
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.addUser': 'إضافة مستخدم',
    'admin.editUser': 'تعديل مستخدم',
    'admin.name': 'الاسم',
    'admin.email': 'البريد الإلكتروني',
    'admin.role': 'الدور',
    
    'admin.enabled': 'مفعل',
    'admin.disabled': 'معطل',
    'admin.grantAccess': 'منح الوصول إلى القسم المالي',
    'admin.financialAccessDesc': 'المستخدمون الذين لديهم هذا التصريح يمكنهم عرض تكاليف الجراحة والمعلومات المالية',
    'admin.fullName': 'الاسم الكامل',
    'admin.emailAddress': 'عنوان البريد الإلكتروني',
    'admin.password': 'كلمة المرور',
    'admin.keepPassword': 'اتركه فارغاً للاحتفاظ بكلمة المرور الحالية',
    'admin.user': 'مستخدم',
    'admin.doctor': 'طبيب',
    'admin.administrator': 'مسؤول',
    'admin.noUsers': 'لم يتم العثور على مستخدمين. أضف أول مستخدم.',
    'admin.cannotDeleteSelf': 'لا يمكنك حذف حسابك الخاص',
    'admin.confirmDeleteUser': 'هل أنت متأكد من حذف هذا المستخدم؟',
    'admin.deleteUser': 'حذف مستخدم',
    'admin.userCreated': 'تم إنشاء حساب مستخدم جديد',
    'admin.userUpdated': 'تم تحديث حساب المستخدم',
    'admin.userDeleted': 'تم حذف حساب المستخدم',
    'admin.saveError': 'تعذر حفظ حساب المستخدم. يرجى التحقق من الاتصال والمحاولة مرة أخرى.',
    'admin.deleteError': 'تعذر حذف حساب المستخدم. يرجى المحاولة مرة أخرى.',
    'admin.financialAccessGranted': 'تم منح الوصول المالي',
    'admin.financialAccessRevoked': 'تم إلغاء الوصول المالي',
    'admin.accessUpdateError': 'تعذر تحديث أذونات الوصول. يرجى المحاولة مرة أخرى.',
    'admin.dataManagement': 'إدارة البيانات',
    'admin.exportDatabase': 'تصدير قاعدة البيانات',
    'admin.importPatients': 'استيراد المرضى',
    'admin.exporting': 'جاري التصدير...',
    'admin.importing': 'جاري الاستيراد...',
    'admin.exportSuccess': 'تم تصدير قاعدة البيانات بنجاح',
    'admin.exportError': 'فشل تصدير قاعدة البيانات',
    'admin.importSuccess': 'تم استيراد المرضى بنجاح',
    'admin.importError': 'فشل استيراد المرضى',
    'admin.importNoData': 'لم يتم العثور على بيانات صالحة في الملف',
    'admin.importPartial': 'فشل استيراد بعض المرضى',
    'admin.exportInfo': 'التصدير:',
    'admin.exportDescription': 'تنزيل قاعدة البيانات الكاملة بصيغة JSON للنسخ الاحتياطي أو النقل.',
    'admin.importInfo': 'الاستيراد:',
    'admin.importDescription': 'استيراد المرضى من ملف CSV/Excel. الأعمدة المطلوبة: الاسم (عربي)، العمر، الجنس، التشخيص، التاريخ، الحالة، الملاحظات.',
    
    // Status
    'status.diagnosed': 'مشخص',
    'status.preOp': 'قبل الجراحة',
    'status.postOp': 'بعد الجراحة',
    
    // Gender
    'gender.male': 'ذكر',
    'gender.female': 'أنثى',
    'gender.other': 'آخر',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', lang);
  };

  useEffect(() => {
    document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

